# Generated by Django 6.0.2 on 2026-02-11 08:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: IELTS Listening Practice Test 2025 | Section 1-4', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, help_text='URL uchun avtomatik generatsiya qilinadi', max_length=250, unique=True)),
                ('youtube_url', models.URLField(help_text="To'liq YouTube video havolasi[](https://www.youtube.com/watch?v=...)", validators=[django.core.validators.URLValidator()], verbose_name='YouTube URL')),
                ('category', models.CharField(choices=[('section_1', 'Section 1 – Everyday Social Conversations'), ('section_2', 'Section 2 – Monologues (speeches, guides)'), ('section_3', 'Section 3 – Academic Discussions'), ('section_4', 'Section 4 – Lectures / Academic Monologues'), ('full_test', 'Full Listening Practice Test'), ('question_type', 'Specific Question Type Practice (Matching, MCQ, etc.)'), ('topic_based', 'Topic-based (Travel, Education, Environment, Work)'), ('tips_tricks', 'Tips & Strategies for IELTS Listening'), ('real_test_simulation', 'Real IELTS Test Simulation')], default='full_test', help_text='Material qaysi turdagi mashq ekanligini belgilaydi', max_length=100, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, help_text="Videoda nimalar borligi haqida qisqa ma'lumot (ixtiyoriy)", max_length=500, verbose_name='Qisqacha tavsif')),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner / Band 4-5.5'), ('intermediate', 'Intermediate / Band 6-7'), ('advanced', 'Advanced / Band 7.5+')], default='intermediate', max_length=20, verbose_name='Qiyinlik darajasi')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text="Videoning taxminiy uzunligi (qo'lda yoki avto hisoblash mumkin)", null=True, verbose_name='Taxminiy davomiylik (daqiqa)')),
                ('is_active', models.BooleanField(default=True, help_text="Faqat faol materiallar talabalar uchun ko'rinadi", verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Listening Material (YouTube)',
                'verbose_name_plural': 'Listening Materiallari (YouTube)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='modules_lis_slug_cfdf5d_idx'), models.Index(fields=['category', 'difficulty', 'is_active'], name='modules_lis_categor_29c741_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: IELTS Listening Practice Test 1', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, help_text="URL uchun avtomatik generatsiya qilinadi (agar bo'sh qoldirilsa)", max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text="Test haqida qisqacha ma'lumot (ixtiyoriy)", verbose_name='Qisqacha tavsif')),
                ('html_file', models.FileField(help_text='Listening testning asosiy HTML fayli (audio + savollar bilan)', upload_to='listening_tests/html/%Y/%m/', verbose_name='HTML fayl')),
                ('cover_image', models.ImageField(blank=True, help_text='Test uchun muqova rasmi (ixtiyoriy)', null=True, upload_to='listening_tests/covers/%Y/%m/', verbose_name='Muqova rasmi')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (Band 5-6)'), ('medium', 'Medium (Band 6-7)'), ('hard', 'Hard (Band 7.5-9)')], default='medium', max_length=20, verbose_name='Qiyinlik darajasi')),
                ('is_active', models.BooleanField(default=True, help_text="Faqat faol testlar talabalar tomonidan ko'rinadi", verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Listening Test',
                'verbose_name_plural': 'Listening Testlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='modules_lis_slug_79de06_idx'), models.Index(fields=['is_active', 'difficulty'], name='modules_lis_is_acti_6c6592_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: The Nature of Memory, Urbanization Trends', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, help_text="URL uchun (agar bo'sh qoldirilsa avto-generatsiya qilinadi)", max_length=250, unique=True, verbose_name='Slug')),
                ('html_content', models.FileField(help_text="Matn, sarlavhalar, rasmlar va formatlash HTML ichida bo'ladi", upload_to='reading_passages/html/%Y/%m/', verbose_name='HTML fayl')),
                ('cover_image', models.ImageField(blank=True, help_text='Passage uchun muqova/illustratsiya (ixtiyoriy)', null=True, upload_to='reading_passages/covers/%Y/%m/', verbose_name='Muqova rasmi')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (Band 5-6)'), ('medium', 'Medium (Band 6-7)'), ('hard', 'Hard (Band 7.5-9)')], default='medium', max_length=20, verbose_name='Qiyinlik darajasi')),
                ('word_count', models.PositiveIntegerField(blank=True, help_text="Matndagi taxminiy so'zlar soni (avto hisoblash mumkin)", null=True, verbose_name="So'zlar soni")),
                ('is_active', models.BooleanField(default=True, help_text="Faqat faol passage talabalar uchun ko'rinadi", verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Reading Passage',
                'verbose_name_plural': 'Reading Passages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='modules_rea_slug_5da38b_idx'), models.Index(fields=['is_active', 'difficulty'], name='modules_rea_is_acti_3a59b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Climate Change, The Benefits of Remote Work', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, help_text="URL uchun (bo'sh qoldirsangiz avtomatik yaratiladi)", max_length=250, unique=True)),
                ('content', models.TextField(help_text="To'liq maqola matni (Markdown yoki oddiy text bo'lishi mumkin)", validators=[django.core.validators.MinLengthValidator(200)], verbose_name='Maqola matni')),
                ('level', models.CharField(choices=[('beginner', 'Beginner (A1–A2)'), ('elementary', 'Elementary (A2–B1)'), ('intermediate', 'Intermediate (B1–B2)'), ('upper_intermediate', 'Upper-Intermediate (B2–C1)'), ('advanced', 'Advanced (C1–C2)')], default='intermediate', help_text="Maqola qaysi darajadagi o'quvchilar uchun mo'ljallangan", max_length=30, verbose_name='Daraja (Level)')),
                ('featured_image', models.ImageField(blank=True, help_text='Maqola uchun asosiy rasm (ixtiyoriy, lekin tavsiya etiladi)', null=True, upload_to='articles/featured/%Y/%m/', verbose_name='Rasm (muqova)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
            ],
            options={
                'verbose_name': 'Smart Article',
                'verbose_name_plural': 'Smart Articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='modules_sma_slug_0a749d_idx'), models.Index(fields=['level'], name='modules_sma_level_e31200_idx')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Masalan: eloquent, run, happiness', max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name="So'z")),
                ('definition', models.TextField(help_text="So'zning asosiy ma'nosi (ingliz tilida yoki o'zbek tilida)", validators=[django.core.validators.MinLengthValidator(10)], verbose_name="Ta'rif / Definition")),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 – Beginner'), ('A2', 'A2 – Elementary'), ('B1', 'B1 – Intermediate'), ('B2', 'B2 – Upper-Intermediate'), ('C1', 'C1 – Advanced'), ('C2', 'C2 – Proficiency')], default='B1', help_text="So'z qaysi CEFR darajasiga tegishli (Common European Framework)", max_length=5, verbose_name='CEFR darajasi')),
                ('example_sentences', models.TextField(blank=True, help_text='Har bir jumla yangi qatordan (one per line)', verbose_name='Misol jumlalar (Example Sentences)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
            ],
            options={
                'verbose_name': 'Vocabulary Word',
                'verbose_name_plural': 'Vocabulary Words',
                'ordering': ['word'],
                'indexes': [models.Index(fields=['word'], name='modules_voc_word_441e93_idx'), models.Index(fields=['cefr_level'], name='modules_voc_cefr_le_d57c9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Environment & Technology, Housing Trends in the UK', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Sarlavha / Mavzu')),
                ('slug', models.SlugField(blank=True, help_text="URL uchun (bo'sh qoldirsangiz avto generatsiya qilinadi)", max_length=250, unique=True)),
                ('topic_category', models.CharField(blank=True, help_text='Masalan: Environment, Education, Technology, Health, Crime', max_length=100, verbose_name='Mavzu kategoriyasi')),
                ('difficulty', models.CharField(blank=True, choices=[('band_5_6', 'Band 5–6'), ('band_6_7', 'Band 6–7'), ('band_7_5_plus', 'Band 7.5+')], default='band_6_7', max_length=20, verbose_name='Taxminiy band darajasi')),
                ('task1_question', models.TextField(blank=True, help_text='Masalan: The chart below shows the percentage of households...', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Task 1 savoli (Graph/Chart/Process/Map)')),
                ('task1_image', models.ImageField(blank=True, help_text='Graph, table, pie chart, bar chart, process diagram yoki map', null=True, upload_to='writing/task1/%Y/%m/', verbose_name='Task 1 diagrammasi / rasmi')),
                ('task1_word_count', models.PositiveSmallIntegerField(default=150, help_text='Odatda 150+', verbose_name="Task 1 minimal so'zlar")),
                ('task1_time_minutes', models.PositiveSmallIntegerField(default=20, verbose_name='Task 1 vaqti (daqiqa)')),
                ('task2_question', models.TextField(blank=True, help_text='Masalan: Some people think that technology makes life more complicated...', validators=[django.core.validators.MinLengthValidator(30)], verbose_name='Task 2 savoli (Essay)')),
                ('task2_essay_type', models.CharField(blank=True, choices=[('', '— tanlanmagan —'), ('opinion', 'Agree / Disagree'), ('discussion', 'Discuss both views'), ('advantages_disadvantages', 'Advantages & Disadvantages'), ('problem_solution', 'Problem & Solution'), ('two_part', 'Two-part question')], default='', max_length=50, verbose_name='Task 2 essay turi')),
                ('task2_word_count', models.PositiveSmallIntegerField(default=250, help_text='Odatda 250+', verbose_name="Task 2 minimal so'zlar")),
                ('task2_time_minutes', models.PositiveSmallIntegerField(default=40, verbose_name='Task 2 vaqti (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_writing_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writing Task (Task 1 + Task 2)',
                'verbose_name_plural': 'Writing Tasklari',
                'ordering': ['-created_at'],
            },
        ),
    ]
