# Generated by Django 6.0.2 on 2026-02-11 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingtask',
            name='created_by',
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vocabularywords', to=settings.AUTH_USER_MODEL),
        ),
    ]
