# Generated by Django 6.0.2 on 2026-02-11 10:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_writingtask_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Mavzu nomi')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
            },
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='imported_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='modules.vocabularyword'),
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'A1 – Beginner'), ('A2', 'A2 – Elementary'), ('B1', 'B1 – Intermediate'), ('B2', 'B2 – Upper-Intermediate'), ('C1', 'C1 – Advanced'), ('C2', 'C2 – Proficiency')], default='B1', max_length=5, verbose_name='CEFR darajasi'),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vocabulary_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='definition',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name="Ta'rif / Definition"),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='example_sentences',
            field=models.TextField(blank=True, help_text='Har bir jumla yangi qatordan yoziladi', verbose_name='Misol jumlalar'),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='word',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name="So'z"),
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to='modules.topic'),
        ),
    ]
