# Generated by Django 6.0.2 on 2026-02-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_topic_vocabularyword_imported_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingtask',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='task1_time_minutes',
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='task1_word_count',
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='task2_time_minutes',
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='task2_word_count',
        ),
    ]
