# Generated by Django 6.0.2 on 2026-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_remove_writingtask_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtask',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy (Band 5-6)'), ('medium', 'Medium (Band 6-7)'), ('hard', 'Hard (Band 7.5-9)')], default='medium', help_text='Writing task qiyinlik darajasi', max_length=20, verbose_name='Qiyinlik darajasi'),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Writing task faol yoki faol emasligini belgilaydi', verbose_name='Faol'),
        ),
    ]
