# Generated by Django 6.0.2 on 2026-02-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_listening_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vip_expires_at',
        ),
    ]
