# Generated by Django 6.0.2 on 2026-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_is_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_band_score',
            field=models.FloatField(blank=True, help_text='Hozirgi tahminiy daraja', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_study_hours',
            field=models.FloatField(blank=True, help_text='Kuniga qancha soat sarflay oladi', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('general', 'General Training')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strong_skills',
            field=models.JSONField(blank=True, help_text="Kuchli tomonlari ['reading', 'speaking']", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weak_skills',
            field=models.JSONField(blank=True, help_text="Zaif tomonlari ['listening', 'writing']", null=True),
        ),
    ]
