# Generated by Django 6.0.2 on 2026-05-31 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0005_writingtask_difficulty_writingtask_is_active'),
        ('subscriptions', '0003_coinservicecost_alter_subscriptionplan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('academic', 'IELTS Academic'), ('general_training', 'IELTS General Training')], default='academic', max_length=20)),
                ('mock_type', models.CharField(choices=[('core', 'Core Mock (Listening + Reading + Writing)'), ('complete', 'Complete Mock (+ Speaking)')], default='core', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (Band 5-6)'), ('medium', 'Medium (Band 6-7)'), ('hard', 'Hard (Band 7.5-9)')], default='medium', max_length=20)),
                ('speaking_questions', models.JSONField(blank=True, help_text="Speaking savollar to'plami: {part1: [...], part2: {...}, part3: [...]}", null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=150)),
                ('is_premium', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mock_exams', to=settings.AUTH_USER_MODEL)),
                ('listening_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_exams', to='modules.listeningtest')),
                ('reading_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_exams', to='modules.readingpassage')),
                ('writing_task1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_exams_task1', to='modules.writingtask')),
                ('writing_task2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_exams_task2', to='modules.writingtask')),
            ],
            options={
                'verbose_name': 'Mock Exam',
                'verbose_name_plural': 'Mock Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('academic', 'IELTS Academic'), ('general_training', 'IELTS General Training')], max_length=20)),
                ('mock_type', models.CharField(choices=[('core', 'Core Mock (Listening + Reading + Writing)'), ('complete', 'Complete Mock (+ Speaking)')], max_length=20)),
                ('access_source', models.CharField(choices=[('subscription_quota', 'Subscription Quota'), ('coin_purchase', 'Coin Purchase'), ('admin_grant', 'Admin Grant'), ('promo', 'Promo Code')], default='subscription_quota', max_length=20)),
                ('coin_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('in_progress', 'In Progress'), ('listening_completed', 'Listening Completed'), ('reading_completed', 'Reading Completed'), ('writing_completed', 'Writing Completed'), ('speaking_pending', 'Speaking Pending'), ('speaking_completed', 'Speaking Completed'), ('processing', 'Processing Results'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='reserved', max_length=25)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('listening_started_at', models.DateTimeField(blank=True, null=True)),
                ('listening_completed_at', models.DateTimeField(blank=True, null=True)),
                ('reading_started_at', models.DateTimeField(blank=True, null=True)),
                ('reading_completed_at', models.DateTimeField(blank=True, null=True)),
                ('writing_started_at', models.DateTimeField(blank=True, null=True)),
                ('writing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('speaking_started_at', models.DateTimeField(blank=True, null=True)),
                ('speaking_completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_section', models.CharField(default='listening', max_length=20)),
                ('current_question', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mockexams.mockexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Exam Attempt',
                'verbose_name_plural': 'Mock Exam Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading')], max_length=20)),
                ('question_number', models.PositiveIntegerField()),
                ('answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mockexams.mockexamattempt')),
            ],
            options={
                'verbose_name': 'Mock Exam Answer',
                'verbose_name_plural': 'Mock Exam Answers',
                'ordering': ['section_type', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='MockExamQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_mock_total', models.PositiveIntegerField(default=0)),
                ('core_mock_used', models.PositiveIntegerField(default=0)),
                ('complete_mock_total', models.PositiveIntegerField(default=0)),
                ('complete_mock_used', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_quotas', to='subscriptions.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Exam Quota',
                'verbose_name_plural': 'Mock Exam Quotas',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='MockExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_correct', models.PositiveIntegerField(default=0)),
                ('listening_total', models.PositiveIntegerField(default=40)),
                ('listening_band', models.FloatField(blank=True, null=True)),
                ('reading_correct', models.PositiveIntegerField(default=0)),
                ('reading_total', models.PositiveIntegerField(default=40)),
                ('reading_band', models.FloatField(blank=True, null=True)),
                ('writing_band', models.FloatField(blank=True, null=True)),
                ('speaking_band', models.FloatField(blank=True, null=True)),
                ('overall_band', models.FloatField(blank=True, null=True)),
                ('skill_breakdown', models.JSONField(blank=True, null=True)),
                ('weak_skills', models.JSONField(blank=True, null=True)),
                ('strong_skills', models.JSONField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('question_type_accuracy', models.JSONField(blank=True, null=True)),
                ('writing_task1_feedback', models.JSONField(blank=True, null=True)),
                ('writing_task2_feedback', models.JSONField(blank=True, null=True)),
                ('speaking_feedback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='mockexams.mockexamattempt')),
            ],
            options={
                'verbose_name': 'Mock Exam Result',
                'verbose_name_plural': 'Mock Exam Results',
            },
        ),
        migrations.CreateModel(
            name='MockSpeakingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking_part', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], max_length=10)),
                ('question_number', models.PositiveIntegerField(default=1)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='mock_speaking/%Y/%m/')),
                ('transcript', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_recordings', to='mockexams.mockexamattempt')),
            ],
            options={
                'verbose_name': 'Mock Speaking Recording',
                'verbose_name_plural': 'Mock Speaking Recordings',
                'ordering': ['speaking_part', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='MockWritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('band_score', models.FloatField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='mockexams.mockexamattempt')),
            ],
            options={
                'verbose_name': 'Mock Writing Submission',
                'verbose_name_plural': 'Mock Writing Submissions',
            },
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['user', 'status'], name='mockexams_m_user_id_fb1052_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['user', 'mock_exam'], name='mockexams_m_user_id_f94192_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockexamanswer',
            unique_together={('attempt', 'section_type', 'question_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mockwritingsubmission',
            unique_together={('attempt', 'task_type')},
        ),
    ]
