# Generated by Django 6.0.2 on 2026-02-09 15:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.PositiveIntegerField(default=0, help_text="Ko'rsatish tartibi (qancha kichik bo'lsa, shuncha oldin)")),
                ('is_active', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('duration_days', models.PositiveIntegerField(help_text='Duration in days for calculation')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this plan')),
                ('max_tests_per_day', models.PositiveIntegerField(blank=True, help_text='Maximum tests allowed per day', null=True)),
                ('max_study_materials', models.PositiveIntegerField(blank=True, help_text='Maximum study materials allowed per month', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions_subscription_plan',
                'ordering': ['priority', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was started')),
                ('auto_renew', models.BooleanField(default=False, help_text='Auto-renew subscription')),
                ('tests_used_today', models.PositiveIntegerField(default=0, help_text='Number of tests used today')),
                ('study_materials_used', models.PositiveIntegerField(default=0, help_text='Number of study materials used')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_user_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_type', models.CharField(choices=[('subscription', 'Subscription'), ('renewal', 'Yangilash'), ('upgrade', 'Yangilash'), ('refund', 'Qaytarish'), ('bonus', 'Bonus')], default='subscription', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('cash', 'Naqt pul'), ('coins', 'Coinlar')], max_length=50)),
                ('payment_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarildi')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Payment gateway response data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.usersubscription')),
            ],
            options={
                'db_table': 'subscriptions_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
