# Generated by Django 6.0.2 on 2026-02-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coins', models.PositiveIntegerField()),
                ('price_uzs', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coin Pack',
                'verbose_name_plural': 'Coin Packlar',
                'ordering': ['price_uzs'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ichki kod (masalan: free, basic_weekly, basic_monthly)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Frontend uchun chiroyli nom (masalan: Free, Basic Weekly)', max_length=150)),
                ('description', models.TextField(blank=True, help_text="Tarif haqida qisqacha ma'lumot", null=True)),
                ('price_uzs', models.PositiveIntegerField(help_text="Narx (so'mda)")),
                ('duration_days', models.PositiveIntegerField(help_text='Obuna davomiyligi (kunlarda, masalan 7 yoki 30)')),
                ('included_coins', models.PositiveIntegerField(default=0, help_text='Obuna olganda beriladigan tanga miqdori')),
                ('is_unlimited_reading', models.BooleanField(default=True)),
                ('is_unlimited_listening', models.BooleanField(default=True)),
                ('is_unlimited_vocab', models.BooleanField(default=True)),
                ('daily_vocab_limit', models.PositiveIntegerField(blank=True, help_text='Kunlik vocab limiti (Free uchun 10, boshqalar uchun None = cheksiz)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Planlar',
                'ordering': ['price_uzs'],
            },
        ),
        migrations.CreateModel(
            name='CoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, help_text='Joriy tangalar soni')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coin Wallet',
                'verbose_name_plural': 'Coin Walletlar',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Musbat (depozit) yoki manfiy (yechish) tanga miqdori')),
                ('type', models.CharField(blank=True, choices=[('subscription_bonus', 'Subscription bonus'), ('coin_shop_purchase', 'Coin shop purchase'), ('welcome_bonus', 'Welcome bonus'), ('writing_evaluation', 'AI Writing Evaluation'), ('speaking_mock', 'AI Speaking Mock'), ('smart_article_translation', 'Smart Article Translation'), ('manual_adjustment', 'Manual adjustment')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_object_id', models.CharField(blank=True, help_text='Masalan, writing attempt ID yoki article ID', max_length=100, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Masalan, writing_attempt, smart_article va hokazo', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.coinwallet')),
            ],
            options={
                'verbose_name': 'Coin Transaction',
                'verbose_name_plural': 'Coin Transactionlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='subscriptio_user_id_0d346a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, choices=[('click', 'Click'), ('payme', 'Payme')], max_length=20, null=True)),
                ('provider_payment_id', models.CharField(blank=True, help_text='Click/Payme tomonidan beriladigan ID (trans_id / transaction_id va hokazo)', max_length=255, null=True)),
                ('amount_uzs', models.PositiveIntegerField(help_text="To'lov summasi (so'mda)")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('extra_data', models.JSONField(blank=True, help_text="Provayderdan kelgan qo'shimcha ma'lumotlar (request/response)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin_pack', models.ForeignKey(blank=True, help_text="Agar bu to'lov coin pack uchun bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.coinpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text="Agar bu to'lov obuna uchun bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_9c57a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(blank=True, help_text='Obuna boshlanish vaqti', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='Obuna tugash vaqti', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_50396b_idx')],
            },
        ),
    ]
