# Generated by Django 6.0.2 on 2026-05-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text="To'lov cheki (screenshot yoki PDF)", null=True, upload_to='payments/receipts/%Y/%m/'),
        ),
    ]
