# Generated by Django 6.0.2 on 2026-05-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_payment_receipt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinServiceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(choices=[('writing_task1', 'Writing Task 1 AI tahlili'), ('writing_task2', 'Writing Task 2 AI tahlili'), ('speaking_part1', 'Speaking Part 1 AI tahlili'), ('speaking_part2', 'Speaking Part 2 AI tahlili'), ('speaking_part3', 'Speaking Part 3 AI tahlili'), ('speaking_full_mock', 'Full Speaking Mock tahlili'), ('full_mock_report', 'Full IELTS Mock Report'), ('ai_tutor', 'Kengaytirilgan AI Tutor javobi')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('cost_coins', models.PositiveIntegerField(help_text='Xizmat narxi (coin)')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coin Service Cost',
                'verbose_name_plural': 'Coin Service Costs',
                'ordering': ['service_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'price_uzs'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Planlar'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='badge',
            field=models.CharField(blank=True, help_text='Masalan: Tavsiya etiladi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_listening_limit',
            field=models.PositiveIntegerField(default=1, help_text='Kunlik Listening section limiti'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_reading_limit',
            field=models.PositiveIntegerField(default=1, help_text='Kunlik Reading passage limiti'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_speaking_ai_limit',
            field=models.PositiveIntegerField(default=5, help_text='Kunlik Speaking AI limiti (fair-use)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_writing_ai_limit',
            field=models.PositiveIntegerField(default=5, help_text='Kunlik Writing AI limiti (fair-use)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_advanced_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_smart_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_weekly_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_launch_price_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='launch_price_uzs',
            field=models.PositiveIntegerField(blank=True, help_text="Launch maxsus narx (bo'lmasa oddiy narx ishlatiladi)", null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='speaking_ai_limit',
            field=models.PositiveIntegerField(default=0, help_text="Tarif ichidagi Speaking AI tahlil limiti (0 = yo'q)"),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='writing_ai_limit',
            field=models.PositiveIntegerField(default=0, help_text="Tarif ichidagi Writing AI tahlil limiti (0 = yo'q)"),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(help_text='Ichki kod (masalan: free, weekly, monthly)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='daily_vocab_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Kunlik vocab limiti (None = cheksiz)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Obuna davomiyligi (kunlarda)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='included_coins',
            field=models.PositiveIntegerField(default=0, help_text='Obuna olganda beriladigan bonus coin'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_unlimited_listening',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_unlimited_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Frontend uchun chiroyli nom', max_length=150),
        ),
    ]
