# Generated by Django 6.0.2 on 2026-05-31 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0005_writingtask_difficulty_writingtask_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('writing_pre_analysis', 'Writing Pre-Analysis'), ('writing_task_1_analysis', 'Writing Task 1 Analysis'), ('writing_task_2_analysis', 'Writing Task 2 Analysis'), ('speaking_transcription', 'Speaking Transcription'), ('speaking_analysis', 'Speaking Analysis'), ('pronunciation_assessment', 'Pronunciation Assessment'), ('mock_report', 'Mock Report'), ('fallback_recheck', 'Fallback Recheck')], max_length=50)),
                ('provider', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('audio_duration_seconds', models.FloatField(default=0)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('fallback_used', models.BooleanField(default=False)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking_type', models.CharField(default='part_1', max_length=30)),
                ('question_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speaking_audio/%Y/%m/')),
                ('audio_duration_seconds', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('quota_source', models.CharField(default='subscription', max_length=30)),
                ('coin_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speaking Attempt',
                'verbose_name_plural': 'Speaking Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('fallback_used', models.BooleanField(default=False)),
                ('assessment_json', models.JSONField()),
                ('estimated_overall_band', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='ai_services.speakingattempt')),
            ],
            options={
                'verbose_name': 'Speaking AI Feedback',
                'verbose_name_plural': 'Speaking AI Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='SpeakingTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('transcript', models.TextField()),
                ('segments', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('fallback_used', models.BooleanField(default=False)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='ai_services.speakingattempt')),
            ],
            options={
                'verbose_name': 'Speaking Transcript',
                'verbose_name_plural': 'Speaking Transcripts',
            },
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(default='task_2', max_length=20)),
                ('content', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='submitted', max_length=20)),
                ('quota_source', models.CharField(default='subscription', max_length=30)),
                ('coin_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
                ('writing_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.writingtask')),
            ],
            options={
                'verbose_name': 'Writing Submission',
                'verbose_name_plural': 'Writing Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingAIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('fallback_used', models.BooleanField(default=False)),
                ('assessment_json', models.JSONField()),
                ('estimated_overall_band', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='ai_services.writingsubmission')),
            ],
            options={
                'verbose_name': 'Writing AI Feedback',
                'verbose_name_plural': 'Writing AI Feedbacks',
            },
        ),
    ]
