# Generated by Django 6.0.2 on 2026-02-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vocab_learned_count', models.PositiveIntegerField(default=0)),
                ('writing_evaluation_count', models.PositiveIntegerField(default=0)),
                ('speaking_mock_count', models.PositiveIntegerField(default=0)),
                ('reading_attempt_count', models.PositiveIntegerField(default=0)),
                ('listening_attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Daily Usage',
                'verbose_name_plural': 'User Daily Usages',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
