# Generated by Django 6.0.2 on 2026-02-09 15:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('pronunciation', 'Pronunciation'), ('comprehension', 'Comprehension'), ('spelling', 'Spelling')], max_length=15)),
                ('user_answer', models.TextField(help_text="User's incorrect answer")),
                ('correct_answer', models.TextField(help_text='Correct answer')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the error')),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_occurrence', models.DateTimeField(auto_now_add=True)),
                ('last_occurrence', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='modules.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attempts_error_log',
                'ordering': ['-last_occurrence'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('study_material', 'Study Material'), ('practice_test', 'Practice Test'), ('video_lesson', 'Video Lesson'), ('exercise', 'Exercise')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_skill', models.CharField(help_text='Target skill to improve', max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Tavsiyaning amal qilish muddati', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.studymaterial')),
                ('related_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attempts_recommendation',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('reading', 'Reading'), ('watching', 'Watching'), ('practicing', 'Practicing')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('minutes_watched', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='modules.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attempts_study_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_type', models.CharField(choices=[('practice', 'Practice'), ('exam', 'Exam'), ('review', 'Review')], default='practice', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_minutes', models.PositiveIntegerField(default=0)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attempts_test_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=10)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveIntegerField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('skipped_questions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='modules.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='attempts.testsession')),
            ],
            options={
                'db_table': 'attempts_section_attempt',
                'ordering': ['-started_at'],
                'unique_together': {('session', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests_taken', models.PositiveIntegerField(default=0)),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('best_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_band', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('target_band', models.DecimalField(decimal_places=1, default=7.0, max_digits=3)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_trackers', to='modules.testcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attempts_progress_tracker',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_answered', 'Not Answered'), ('answered', 'Answered'), ('skipped', 'Skipped'), ('flagged', 'Flagged')], default='not_answered', max_length=15)),
                ('selected_answer', models.CharField(blank=True, help_text='Multiple choice javobi', max_length=500, null=True)),
                ('written_answer', models.TextField(blank=True, help_text='Written answer', null=True)),
                ('matching_answers', models.JSONField(blank=True, default=dict, help_text='Matching answers')),
                ('answer_data', models.JSONField(blank=True, default=dict, help_text="User's answer in JSON format")),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.question')),
                ('section_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='attempts.sectionattempt')),
            ],
            options={
                'db_table': 'attempts_question_response',
                'unique_together': {('section_attempt', 'question')},
            },
        ),
    ]
